"""
Django settings for psbs project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import datetime
# import s3utils
# from storages.backends.s3boto import S3BotoStorage
#
# StaticRootS3BotoStorage = lambda: S3BotoStorage(location='static')
# MediaRootS3BotoStorage = lambda: S3BotoStorage(location='media')

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'


# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = False

# Allow all host headers
ALLOWED_HOSTS = ['*']

FULL_DOMAIN_NAME = 'https://projectstepbystep.herokuapp.com'

# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'accounts',
    'analytics',
    'billing',
    'comments',
    'notifications',
    'videos',
	'storages',
)

CRISPY_TEMPLATE_PACK = 'bootstrap3'

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'psbs.urls'

LOGIN_URL = "/login/"

AUTH_USER_MODEL = 'accounts.MyUser'

RECENT_COMMENT_NUMBER = 10

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATE_CONTEXT_PROCESSORS = (
    "django.contrib.auth.context_processors.auth",
    "django.core.context_processors.debug",
    "django.core.context_processors.i18n",
    "django.core.context_processors.media",
    "django.core.context_processors.request",
    "django.core.context_processors.static",
    "django.core.context_processors.tz",
    "django.contrib.messages.context_processors.messages"
)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

WSGI_APPLICATION = 'psbs.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# STATIC_URL = '/static/'
#
# MEDIA_URL = '/media/'

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#
# MEDIA_ROOT = os.path.join(BASE_DIR, 'mediafiles')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'staticfiles_dirs'),
)

# braintree info
BRAINTREE_MERCHANT_ID = "xxxxxxxxxxxxxxxxxxxx"

BRAINTREE_PUBLIC_KEY = "xxxxxxxxxxxxxxxxxxxx"

BRAINTREE_PRIVATE_KEY = "xxxxxxxxxxxxxxxxxxxx"

# AWS production
access_key = 'xxxxxxxxxxxxxxxxxxxx'
secret_key = 'xxxxxxxxxxxxxxxxxxxx'

AWS_ACCESS_KEY_ID = access_key
AWS_SECRET_ACCESS_KEY = 'xxxxxxxxxxxxxxxxxxxx'
AWS_STORAGE_BUCKET_NAME = 'xxxxxxxxxxxxxxxxxxxx'

# static files like css/js/img
STATICFILES_STORAGE = 'psbs.s3utils.StaticRootS3BotoStorage'
# STATICFILES_STORAGE = 'StaticRootS3BotoStorage'
# media uploads
DEFAULT_FILE_STORAGE = 'psbs.s3utils.MediaRootS3BotoStorage'
# DEFAULT_FILE_STORAGE = 'MediaRootS3BotoStorage'

S3_URL = '//%s.s3.amazonaws.com/' % AWS_STORAGE_BUCKET_NAME
MEDIA_URL = S3_URL + 'media/'
STATIC_URL = S3_URL + 'static/'
ADMIN_MEDIA_PREFIX = STATIC_URL + 'admin/'

date_two_months_later = datetime.date.today() + datetime.timedelta(2 * 365 / 12)
expires = date_two_months_later.strftime('%A, %d %B %Y 20:00:00 GMT')

AWS_HEADERS = {
	'Expires': expires,
	'Cache-Control': 'max-age=86400',
}



# settings for production in Heroku
if not DEBUG:
    # Parse database configuration from $DATABASE_URL
    try:
        import dj_database_url

        DATABASES['default'] = dj_database_url.config()
    except:
        pass

    # Honor the 'X-Forwarded-Proto' header for request.is_secure()
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    STATIC_ROOT = STATICFILES_STORAGE
